### ISSUE TITLE
Hide tooltip after button click

### ISSUE THREAD

**Issue by KhaVNguyen** [alterebro/css-tooltip#3]
Love this library.
Wondering if there's a way to hide the tooltip automatically after a button has been pressed? Seems like the tooltip remains and only hides after I click elsewhere

**Comment by KhaVNguyen** [comment]
Got it!
Just have to add this somewhere in your css:
```css
[data-tooltip]:focus:before,
[data-tooltip]:focus:after,
[data-tooltip]:active:before,
[data-tooltip]:active:after {
  opacity: 0 !important;
}
```
